version: '3.9'                   

services:
  web:
    build:                      
      context: .
      dockerfile: Dockerfile
    image: my-fastapi-app
    container_name: fastapi_web   
    ports:
      - "8000:8000"               
    volumes:
      - .:/app                    
    environment:
      - PYTHONUNBUFFERED=1       
    command:                      
      - uvicorn
      - src.api.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
